-- liquibase formatted sql

-- changeset katyshev:createEventTable

CREATE TABLE event
(
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    chatId BIGINT NOT NULL,
    event varchar(100),
    create_time timestamp
)

-- changeset katyshev:addDurationColumn

ALTER TABLE event ADD COLUMN duration BIGINT;
